config/routes.rb
Rails.application.routes.draw do

  resources :artifacts
  resources :tenants do
    resources :projects
  end

  resources :members
  get 'home/index'

  root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
      :registrations => "milia/registrations",
      :confirmations => "confirmations",
      :sessions => "milia/sessions",
      :passwords => "milia/passwords",
  }


end

app/models/artifact.rb
class Artifact < ActiveRecord::Base
  belongs_to :project
  attr_accessor :upload

  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload

  validates_uniqueness_of :name


  validate :uploaded_file_size


  def uploaded_file_size

    if upload

      errors.add(:upload, "File size must be less than #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE

    end

  end
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: [:show, :edit, :update, :destroy]

  # GET /artifacts
  # GET /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1
  # GET /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts
  # POST /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to @artifact, notice: 'Artifact was successfully created.' }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1
  # PATCH/PUT /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: 'Artifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1
  # DELETE /artifacts/1.json
  def destroy
    @artifact.destroy
    respond_to do |format|
      format.html { redirect_to artifacts_url, notice: 'Artifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artifact_params
      params.require(:artifact).permit(:name, :key, :project_id)
    end
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/views/artifacts/_form.html.erb
<%= form_for(@artifact) do |f| %>
  <% if @artifact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
      <% @artifact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artifacts/edit.html.erb
<h1>Editing Artifact</h1>

<%= render 'form' %>

<%= link_to 'Show', @artifact %> |
<%= link_to 'Back', artifacts_path %>

app/views/artifacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artifacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artifacts.each do |artifact| %>
      <tr>
        <td><%= artifact.name %></td>
        <td><%= artifact.key %></td>
        <td><%= artifact.project %></td>
        <td><%= link_to 'Show', artifact %></td>
        <td><%= link_to 'Edit', edit_artifact_path(artifact) %></td>
        <td><%= link_to 'Destroy', artifact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artifact', new_artifact_path %>

app/views/artifacts/new.html.erb
<h1>New Artifact</h1>

<%= render 'form' %>

<%= link_to 'Back', artifacts_path %>

app/views/artifacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artifact.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @artifact.key %>
</p>

<p>
  <strong>Project:</strong>
  <%= @artifact.project %>
</p>

<%= link_to 'Edit', edit_artifact_path(@artifact) %> |
<%= link_to 'Back', artifacts_path %>